---
title: "Final Project - First Draft"
author: "Seyed Hamed Ghodsi"
date: "Deadline: November 8, 2018"
output: html_document
---

***
# Inroduction

This project provides documentation for the analysis of an anonymous city sewer collection system. The purpose of this report is to provide the interpretation of **SWMM** output files.  
EPA's Stormwater Management Model (SWMM) is used for single event or long-term simulations of water runoff quantity and quality in primarily urban areas–although there are also many applications that can be used for drainage systems in non-urban areas. It is used throughout the world for planning, analysis, and design related to stormwater runoff, combined and sanitary sewers, and other drainage systems.  
The SWMM output would be made in two files. The first one is a report file (".rpt") which includes all the cumulative results from the simulation model such as runoff and outfall loading summary. The second one is a binary file (".out") which include the time series analysis of different elements of the model like subcatchments, nodes and links. Usually researchers use SWMM software interface to analyze the time series result, which is stored in the binary file. However, in this report the analysis would be done using `R`. As a result, Therefore, the result would be analyzed and showed in two separated parts.  

***  

# Data


